version: '3'
services:
  ftts_back_end_main:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "10019:8000"
    runtime: nvidia
#    command:
#      - uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    command: [
      "uvicorn",
      "main:app",
      "--host", "0.0.0.0",
      "--port", "8000",
      "--reload" ]
    volumes:
      - .:/workspace

#  tensorboard:
#    image: hsh0322/las-pytorch
#    volumes:
#      - ./:/opt/project
#    ports:
#      - "6006:6006"
#    command: tensorboard --logdir=log/las_timit --port=6006 --host=0.0.0.0

# PowerShell.exe -ExecutionPolicy Bypass -File wsl_port_forward.ps1
