version: '3'
services:
  ftts_back_end:
    build: .
    stdin_open: true
    tty: true
    runtime: Nvidia
    ports:
      - "8000:8000"
    command: [
      "uvicorn",
      "main:app",
      "--host", "0.0.0.0",
      "--port", "8000",
      "--reload" ]
    volumes:
      - .:/workspace
