version: '3'
services:
  ftts_back_end:
    build: .

    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "10019:8000"
#    runtime: nvidia
#    command:
#      - uvicorn main:app --host 0.0.0.0 --port 8000 --reload

    command: [
      "uvicorn",
      "main:app",
      "--host", "0.0.0.0",
      "--port", "8000",
      "--reload" ]
    volumes:
      - .:/workspace
