# version: "3.7"

# services:
# #  mysql:
# #    image: mysql:8.0.31
# #    ports:
# #      - 3306:3306
# #    container_name: "mysql"
# #    environment:
# #      - MYSQL_ROOT_PASSWORD=0000
# #      - MYSQL_DATABASE: ftts

#   fastapi:
#     image: "fastapi"
# #    platform: "linux/amd64"
#     build:
#       context: .
#     command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
#     ports:
#       - 8000:8000
#     volumes:
# #      - /var/jenkins_home/workspace/backEndServer/:/code/
#       - /home/ubuntu/workspace/jenkins/workspace/backEndServer:/code
# #      - /home/ubuntu/workspace/:/code/
# #    extra_hosts:
# #      - "host.docker.internal:host-gateway"

version: '3'
services:
  ftts_back_end:
#    image: pytorch/pytorch:1.7.1-cuda11.0-cudnn8-devel
#    image: pytorch/pytorch:1.12.1-cuda11.3-cudnn8-devel
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "10019:8000"
#    runtime: nvidia
#    command:
#      - uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    command: [
      "uvicorn",
      "main:app",
      "--host", "0.0.0.0",
      "--port", "8000",
      "--reload" ]
    volumes:
      - .:/workspace
    environment:
      NVIDIA_VISIBLE_DEVICES: all

#  tensorboard:
#    image: hsh0322/las-pytorch
#    volumes:
#      - ./:/opt/project
#    ports:
#      - "6006:6006"
#    command: tensorboard --logdir=log/las_timit --port=6006 --host=0.0.0.0

# PowerShell.exe -ExecutionPolicy Bypass -File wsl_port_forward.ps1
