"""empty message

Revision ID: 51c49e372875
Revises: 9ff127d1257d
Create Date: 2023-01-10 16:48:03.501956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c49e372875'
down_revision = '9ff127d1257d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('image_name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('picture', 'image_name')
    # ### end Alembic commands ###
